# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
_: {
  flake.modules.nixos."host/Laptop" =
    {
      config,
      lib,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-5d79646f-89d6-417a-b18b-8dfbc989dba2";
        fsType = "btrfs";
      };

      boot.initrd.luks.devices."luks-5d79646f-89d6-417a-b18b-8dfbc989dba2".device =
        "/dev/disk/by-uuid/5d79646f-89d6-417a-b18b-8dfbc989dba2";

      fileSystems."/home" = {
        device = "/dev/mapper/luks-5d79646f-89d6-417a-b18b-8dfbc989dba2";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };

      fileSystems."/nix" = {
        device = "/dev/mapper/luks-5d79646f-89d6-417a-b18b-8dfbc989dba2";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/248C-F534";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
